language: ruby
rvm:
- 2.1.1
- 2.1.0
env:
  global:
    secure: YwsBXkYk14OKUktZNM6FkUuhu7Y1xeDyDqb4Trkod18iAbH/h8ZzM62xQLWRL2mkPgtnc0nO9yW1S9V23HP9+SlqsyU9ShMa9DLRU8upx/ZM97okaCBn0CCAKjuTDzb28pMVFGRb1VNKSNuPRdbizCEUeNamD6YWq37pSPE6Cn0=
before_script:
- bundle exec rake jetty_setup:test
- mysql -e 'create database aath_search_test;'
notifications:
  slack:
    secure: CudGmLuuCYkUJJI8l6CDmpf9UOudHALoMZea31YZvSehMvL79T7Se0COf2TnJfzUPu3HliEwN4AZqok/BZWlQ7N8Yh2p5Lf3MDuHdZmsEVjcippe8oA0yi42S2ehLIIbbXckpIz4A3NCkbt9lXDJD8rqf6M5wi5BQMpEzAL15VU=
global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true