sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
- 2.1.0
env:
  global:
  - GOOGLE_KEY_FILE="$TRAVIS_BUILD_DIR/config/ga_keyfile.p12"
  - secure: YwsBXkYk14OKUktZNM6FkUuhu7Y1xeDyDqb4Trkod18iAbH/h8ZzM62xQLWRL2mkPgtnc0nO9yW1S9V23HP9+SlqsyU9ShMa9DLRU8upx/ZM97okaCBn0CCAKjuTDzb28pMVFGRb1VNKSNuPRdbizCEUeNamD6YWq37pSPE6Cn0=
  - secure: huNH8Nq2xZWHDA3NsDa9HVzJhtS/FHb7LwDEqF4nVRRU9afTSTcNAzpWPi0gA9WjJMHttUeE+Z7JAth0RuBlTdgNT/grr2emHO6n4x9ZPvtwpphObZhxhBf4CfSBWAVFxGZXwQHddF4kdis3mM/VJ10fQXCtqjmM6rzAAuFgZng=
  - secure: ZfuNhHrRcL72bVdGtet/c51SeoKW+WYiHosJpkedPoIhJ9p68twMzhJTKrLeqaXI4oVbkOeHcYgAAyZgApLvwYjop3ZO0zpG+5OipyfhAgRaHHT35Bu5hsUq8QX8ZpwOW95HfN11wTsPc8XRfaFhmOjUXi/LgvvY5tj3ZlNyXuo=
  - secure: r3eY4xMMv86pBWtNycZNnCkCMIdfVnWnrIPOcbarfkCo/hYgaJiblLFv+uGo3NsiEuGJxNVsVi2VzPESOpjkWkKlt2/nfR9l4E6mkFPJo2hzGpQPcn3ZsDNNAn0hq9j6UT8hIO10DYtGLQs0Oy55KJ5PFCw6agtOn+kuccQSrao=
before_script:
- bundle exec rake solr:setup_test
- mysql -e 'create database aath_search_test;'
- bundle exec rake db:migrate
- bundle exec rake db:seed
notifications:
  slack:
    secure: CudGmLuuCYkUJJI8l6CDmpf9UOudHALoMZea31YZvSehMvL79T7Se0COf2TnJfzUPu3HliEwN4AZqok/BZWlQ7N8Yh2p5Lf3MDuHdZmsEVjcippe8oA0yi42S2ehLIIbbXckpIz4A3NCkbt9lXDJD8rqf6M5wi5BQMpEzAL15VU=
global_env:
- NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
- openssl aes-256-cbc -K $encrypted_997cf1aa5b08_key -iv $encrypted_997cf1aa5b08_iv
  -in config/ga_keyfile.p12.enc -out config/ga_keyfile.p12 -d
