version: '2'
services:
  solr:
    image: lib-docker.artifactory.umn.edu/umbra_solr
    ports:
      - "8983:8983"
    volumes:
      - ./snapshots:/snapshots
  web:
    build: .
    env_file:
      - .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/umbra.search
    ports:
      - "3000:3000"
    links:
      - solr
      - db
      - redis
    depends_on:
      - solr
  db:
    image: library/mysql:5.6.22
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: umbra
    volumes:
      - umbra-db-data:/var/lib/mysql
      - ./docker/data:/docker-entrypoint-initdb.d
  sidekiq:
    build: .
    command: bundle exec sidekiq -r /umbra.search
    volumes:
      - .:/umbra.search
    links:
      - redis
    env_file:
      - .env
  redis:
    image: redis:latest
volumes:
  umbra-db-data:
    driver: local