version: '3'
services:
  solr:
    image: umbra_solr:dev
    ports:
      - "8983:8983"
    volumes:
      - ./snapshots:/snapshots
  web:
    build: .
    env_file:
      - .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/umbra.search
    ports:
      - "3000:3000"
    links:
      - solr
      - db
      - redis
    depends_on:
      - solr
  db:
    image: library/mysql:5.6.22
    volumes:
      - umbra-db-data:/var/lib/mysql
      - ./docker/data:/docker-entrypoint-initdb.d
  sidekiq:
    build: .
    command: bundle exec sidekiq -r /umbra.search
    volumes:
      - .:/umbra.search
    links:
      - redis
    env_file:
      - .env
  redis:
    image: redis:latest
  redis_cache:
    image: redis:4.0.10
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
        - ./docker/redis-cache.conf:/usr/local/etc/redis/redis.conf

volumes:
  umbra-db-data:
    driver: local